app:
  jwt:
    secret: "iw3uetgdrouq36ye8723teuwdakfyyudhetr73yut933ryruhgfjg"
    access-token-expires-ms: 3600000
    refresh-token-expires-ms: 604800000
  payment:
    vnpay:
      tmn-code: yours
      hash-secret: yours
      url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      return-url: http://localhost:8081/api/payments/vnpay-callback
    momo:
      partner-code: yours
      access-key: yours
      secret-key: atQs0nSXYs9iw9Z8792mUn7VS7yVmiF4
      endpoint: https://test-payment.momo.vn/v2/gateway/api/create
      return-url: http://localhost:8081/api/payments/momo-callback
  cloudinary:
    cloud-name: yours
    api-key: yours
    api-secret: yours
  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: "yours"
      password: "yours"
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
