# spring.application.name=backend
# spring.devtools.restart.enabled=false
server.port=8081

spring.profiles.active=dev-h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
rabbit.order.queue=order_notification_queue