app:
  jwt:
    secret: "iw3uetgdrouq36ye8723teuwdakfyyudhetr73yut933ryruhgfjg"
    access-token-expires-ms: 3600000
    refresh-token-expires-ms: 604800000
  payment:
    vnpay:
      tmn-code: IVN0ZMWM
      hash-secret: DWNZDYT99VTGXXDDMD59VNBGR6ROY5HP
      url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      return-url: http://localhost:8081/api/payments/vnpay-callback
    momo:
      partner-code: MOMOBKUN20180529
      access-key: klm05nu13s1puph7
      secret-key: atQs0nSXYs9iw9Z8792mUn7VS7yVmiF4
      endpoint: https://test-payment.momo.vn/v2/gateway/api/create
      return-url: http://localhost:8081/api/payments/momo-callback
  cloudinary:
    cloud-name: dt3btnnxy
    api-key: 463966291979622
    api-secret: qh9cOXw9UUo-BKRyFl6OTY-FYis
  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: "thutrinh2442@gmail.com"
      password: "gtjmgvanxmjsrxdb"
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true