spring.datasource.url=jdbc:mysql://localhost:3306/restdb?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=admin123@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

cloudinary.cloud-name=dt3btnnxy
cloudinary.api-key=463966291979622
cloudinary.api-secret=qh9cOXw9UUo-BKRyFl6OTY-FYis


app.jwt.secret=iw3uetgdrouq36ye8723teuwdakfyyudhetr73yut933ryruhgfjg
app.jwt.access-token-expires-ms=3600000
app.jwt.refresh-token-expires-ms=604800000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thutrinh2442@gmail.com
spring.mail.password=gtjmgvanxmjsrxdb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.payment.vnpay.tmn-code=IVN0ZMWM
app.payment.vnpay.hash-secret=DWNZDYT99VTGXXDDMD59VNBGR6ROY5HP
app.payment.vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
app.payment.vnpay.return-url=http://localhost:8081/api/payments/vnpay-callback


app.payment.momo.partner-code=MOMO
app.payment.momo.access-key=F8BBA842ECF85
app.payment.momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz
app.payment.momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
app.payment.momo.return-url=http://localhost:8081/api/payments/momo-callback